### ISSUE TITLE
Make -exactpositionresolve option affecting symbols of TypeDefault and TypeEnum symbol type (patch attached)

### ISSUE THREAD

**Issue by litvindev** [thoni56/c-xrefactory#13]
[0002-Make-exactpositionresolve-option-affecting.patch.txt](https://github.com/thoni56/c-xrefactory/files/1051809/0002-Make-exactpositionresolve-option-affecting.patch.txt)

SCENARIO 1

1) `git clone git://anongit.freedesktop.org/systemd/systemd`
2) add a new project section to .c-xrefrc:
```
[/home/litvin/src/systemd]
  /home/litvin/src/systemd
  -refs /home/litvin/CXrefs/src/systemd
  -refnum=100
  -exactpositionresolve
```
3) Create references:
`c-xref -create -xrefrc /home/litvin/.c-xrefrc -p /home/litvin/src/systemd -user 1 -xrefactory-II -crlfconversion -crconversion -encoding=default -exactpositionresolve -o /tmp/c-xref-test-systemd.log`

4) Visit this file in Emacs: /home/litvin/src/systemd/src/network/networkd.c and point cursor to "Manager" here:
```
int main(int argc, char *argv[]) {
        _cleanup_manager_free_ Manager *m = NULL;
```
5) Execute "c-xref-push-and-goto-definition" command:
--->  
Right definition was expecting. 
Wrong definition (but with the same name) happened instead.

6) Point cursor to "manager_new" here:
```
int main(int argc, char *argv[]) {
...
        r = manager_new(&m);
```
7) Execute "c-xref-push-and-goto-definition" command:
--->  
Right definition was expecting. 
Wrong definition (but with the same name) happened instead.

SCENARIO 2

```
struct S
{
  int i;
};

int main()
{
  struct S
  {
    int j;
  };

  struct S s; // try c-xref-push-and-goto-definition on S here
  s.j = 1; // try c-xref-push-and-goto-definition on j here

  return 0;
}
```

**Comment by litvindev** [comment]
Also consider a variant to remove "-exactpositionresolve" option and make it behavior by default.

**Comment by thoni56** [comment]
5. What were you expecting?
6. What happened instead?

A smaller example that also can be used as a test case like the other ones in /tests/* would also be much appreciated.

**Comment by litvindev** [comment]
5. Right definition was expecting.
6. Wrong definition (but with the same name) happened instead.

**Comment by thoni56** [comment]
Is it possible to recreate the problem with a smaller example, and perhaps point to the data in the CXref-files that becomes wrong?

**Comment by litvindev** [comment]
See "-exactpositionresolve" option description here:
http://xrefactory.com/xrefactory-java/oldversions.html

A new flavor has emerged since 1.5 version for struct/union link-names.
I've just made it available for typedefs and enums also.

**Comment by litvindev** [comment]
I've made "-exactpositionresolve" flavor available for symbols of TypeDefault symbol type also and updated the patch.

Now this also fixes issue #9

**Comment by litvindev** [comment]
Updated patch (add head.h).

**Comment by thoni56** [comment]
Leaving this open to ponder if `-exactpositionresolve` should be made the default. It makes fast updates impossible and forces full updates according to the code in `checkExactPositionUpdate()`.

**Comment by litvindev** [comment]
You are right, Mr. Nilefalk, it is better to leave "-exactpositionresolve" as is.

**Comment by thoni56** [comment]
So I'll close this.
