### ISSUE TITLE
Patch

### ISSUE THREAD

**Issue by rrthomas** [thoni56/c-xrefactory#33]
[xref-1.6.10.el.diff.txt](https://github.com/thoni56/c-xrefactory/files/2064716/xref-1.6.10.el.diff.txt)

This is a patch against the latest non-free version of XRef which fixes some small problems.

I quite understand if it's useless to you, but I thought it worth submitting just in case!

**Comment by thoni56** [comment]
Thanks, @rrthomas!

Do you know anything more about what this patch does? Looks like it's just a tiny fix to some elisp that adds a check against `eobp`, which checks if point is at end of the buffer.

It also looks like this is already in the "current" sources. But thanks anyway!

**Comment by rrthomas** [comment]
That's right, it's a tiny fix as you say. I'm glad it's in the current sources already; I sent it to Marián a couple of times, but never had an acknowledgement. Since he did usually acknowledge my emails, I assumed the patch had not been applied.
