### ISSUE TITLE
CreateXrefDistribution bug under Linux: missing doc/readme

### ISSUE THREAD

**Issue by shelandy** [thoni56/c-xrefactory#4]
Line 22:
cat doc/INSTALL doc/readme doc/readme2 > ../c-xref/README

doc/readme not found.  
Besides the readme2, I can see only README READMETOP readme.win, but not readme.  I do not know which one you intend to copy to the /c-xref/README

**Comment by thoni56** [comment]
My guess would be that this is a case problem caused by Marian and team developing on a non-case sensitive platform. I've changed to uppercase as that seems to fit.
