### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by thoni56** [thoni56/c-xrefactory#55]
For C a refactoring I miss is "Rename file". It would not only rename the file, but also fixup all the includes that are referencing the file.

Actually, an even better version of this would be "Rename module". Often a C "module" has a '.h' and a '.c' file and inside the header file there is something like

    #ifndef _MODULE_H_
    #define _MODULE_H_

Renaming all of these in a single swoop would be cool.

**Comment by shanemd** [comment]
Duplicate of #48?

**Comment by thoni56** [comment]
Thanks for pointing that out!
