### ISSUE TITLE
Added "#pragma once" directive support (patch attached).

### ISSUE THREAD

**Issue by litvindev** [thoni56/c-xrefactory#6]
[0001-Added-pragma-once-directive-support.patch.txt](https://github.com/thoni56/c-xrefactory/files/667794/0001-Added-pragma-once-directive-support.patch.txt)

**Comment by thoni56** [comment]
Thank you for your patch. Can you supply a case where this fails and how?

**Comment by litvindev** [comment]
Scenario:
1) `git clone git://anongit.freedesktop.org/systemd/systemd`
2) add a new project section to .c-xrefrc:
```
[/home/litvin/src/systemd]
  /home/litvin/src/systemd
  -refs /home/litvin/CXrefs/src/systemd
  -refnum=100
  -exactpositionresolve
```
3) `c-xref -create -xrefrc /home/litvin/.c-xrefrc -p /home/litvin/src/systemd -user 1 -xrefactory-II -crlfconversion -crconversion -encoding=default -exactpositionresolve -o /tmp/c-xref-test-systemd.log`
--->
The program ends up with fatal error:
`fatalError(ERR_ST,"too deep nesting in includes", XREF_EXIT_ERR);`

Because it skips #pragma directives which causes infinite inclusion.

**Comment by thoni56** [comment]
Thanks. I could repeat that problem, getting "fatalError" in the log file.

**Comment by thoni56** [comment]
With the fix in 	https://github.com/thoni56/c-xrefactory/commit/9ec1ccffdc67680e6f430d4f4adb9c718fb89593 the analysis get past the nesting problem. But for me the command never seemed to terminate anyway, it kept spitting out higher and higher numbers, I let it run to 10k before stopping it.

Did you get that too? Do you think this is related to #7  that you also reported?

**Comment by thoni56** [comment]
The loop I got was probably some spurious problem. Works now.
