### ISSUE TITLE
Problem with restoring regs after longjmp (causes infinite loop, patch included)

### ISSUE THREAD

**Issue by litvindev** [thoni56/c-xrefactory#7]
[0001-Problem-with-restoring-regs-after-longjmp.patch.txt](https://github.com/thoni56/c-xrefactory/files/670204/0001-Problem-with-restoring-regs-after-longjmp.patch.txt)

**Comment by thoni56** [comment]
Thanks, can you give a more detailed description when this happens, please?

**Comment by litvindev** [comment]
Scenario:
1) The source code size must be enough to provoke swapping references on disk:
`git clone git://source.ffmpeg.org/ffmpeg.git`
2) Add a new project section to .c-xrefrc:
```
[/home/litvin/src/ffmpeg]
  /home/litvin/src/ffmpeg
  -refs /home/litvin/CXrefs/src/ffmpeg
  -refnum=100
  -exactpositionresolve
```
3) c-xref -create -xrefrc /home/litvin/.c-xrefrc -p /home/litvin/src/ffmpeg -user 1 -xrefactory-II -crlfconversion -crconversion -encoding=default -exactpositionresolve -o /tmp/c-xref-test-ffmpeg.tmp
--> 
The program will never end up.

In my case access to object designated by "ffc" identifier is optimized with register.

```
void mainCallXref(int argc, char **argv) {
	...
      	ffc = pffc = mainCreateListOfInputFiles();
        ...
	for(;;) {
                ...
		if ((mess=setjmp(cxmemOverflow))!=0) {
			mainReferencesOverflowed(cxFreeBase,mess);
                        ...
		} else {
                        ...
			for(; ffc!=NULL; ffc=ffc->next) {
				mainXrefOneWholeFileProcessing(argc, argv, ffc, &firstPassing, &atLeastOneProcessed);
                                ...
			}
                        ...
```
