### ISSUE TITLE
Feature request: Extract function enhancement - suggest to replace duplicate code

### ISSUE THREAD

**Issue by shanemd** [thoni56/c-xrefactory#71]
I've read that some refactoring tools have a feature where they will suggest other places in the code that could be replaced with a function call to a newly extracted function. This sounds like a useful feature to have.

**Comment by thoni56** [comment]
Yes definitely, and that is handy but impossible with the way `c-xrefactory` does things. It has no AST, it only works with the texts and comparing similar source text would definitely not be safe refactoring.
