### ISSUE TITLE
Multiple declarations of same identifier in different modules in a large source tree confuses c-xrefactory

### ISSUE THREAD

**Issue by thoni56** [thoni56/c-xrefactory#9]
In a large source tree there might be duplicate filenames and function names within different modules.

E.g. given

           module1 - void func(int i) {}
         /
    src -  module2 - void func(double d) {}
         \
           main - func(3.14);

In this case `c-xrefactory`, given "sourcedir=src" will misinterpret both `func()` to be the same definition and navigation will cirlcle over all of them.
 
This should really be solved by `c-xrefactory` "knowing" about the compilation and linking structure, but that is probably not feasible.

The solution now is to refrain from using `src` as the source directory, instead enumerating `main` and `module2`. In a large source tree this can be cumbersome and error-prone.

A better option might be to allow "ignored" paths within the source tree, in this case set "sourcedir=src" but ignore `module1`.

**Comment by litvindev** [comment]
This could be solved by adding function parameters to function link-name (which is stored in Xdddd files).
